# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: api.gouv.fr
baseurl: "/api.gouv.fr"
url: "https://api.gouv.fr"
description: Fabriquez des services en ligne plus simples

collections:
  api:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: api	# targets a collection
    values:
      layout: api
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default
      logo: /img/logo-generique-startup-carre.jpg



# vertical-rhythm
api_type:
  - id: confidential
    name: Données confidentielles
    description: Accès sécurisé à des données confidentielles d'un ou d'une entreprise

  - id: reference
    name: Données de référence
    description: Aide à la saisie & contrôle de cohérence vis à vis données de référence tabulaires ou géographiques

  - id: simulation
    name: Calcul et simulation
    description: "Le droit exécutable : éligibilité et calculs fiscaux & sociaux, pour entreprises et particuliers"

  - id: smartData
    name: Smart Data
    description: Accès à des données temps-réel et à des algorithmes exploitant des Big Data

# Build settings
markdown: kramdown
