# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: api.gouv.fr
baseurl: ""
url: "https://api.gouv.fr"
description: Fabriquez des services en ligne plus simples

# see https://jekyllrb.com/docs/continuous-integration/
exclude: [vendor, app.json, Gemfile.lock]

collections:
  api:
    output: true
    permalink: /explorer/:path/
  service:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: api	# targets a collection
    values:
      layout: api
      default_logo: logo-generique-startup-carre.jpg

  -
    scope:
      path: ""	# means "all files"
      type: service	# targets a collection
    values:
      layout: service
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

api_category:
  - id: confidential
    name: Données confidentielles
    logo: privacy
    description: Accès sécurisé à des données confidentielles d'un particulier ou d'une entreprise

  - id: reference
    name: Données de référence
    logo: sitemap
    description: Aide à la saisie & contrôle de cohérence vis à vis données de référence

  - id: simulation
    name: Le droit exécutable
    logo: cogs
    description: "Calcul et simulation : éligibilité et calculs fiscaux & sociaux, pour entreprises et particuliers"

  - id: smartData
    name: Big Data
    logo: magic
    description: Accès à des données temps-réel et à des algorithmes valorisant des données massives

markdown: kramdown
