# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: api.gouv.fr
baseurl: ""
url: "https://api.gouv.fr"

collections:
  api:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: api	# targets a collection
    values:
      layout: api
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default
      logo: /img/logo-generique-startup-carre.jpg



# vertical-rhythm
api_type:
  - id: confidential
    name: Données confidentielles
    description: Accès sécurisé à des données confidentielles d'un ou d'une entreprise

  - id: reference
    name: Données de référence
    description: Aide à la saisie & contrôle de cohérence vis à vis données de référence tabulaires ou géographiques

  - id: simulation
    name: Calcul et simulation
    description: "Le droit exécutable : éligibilité et calculs fiscaux & sociaux, pour entreprises et particuliers"

  - id: smartData
    name: Smart Data
    description: Accès à des données temps-réel et à des algorithmes exploitant des Big Data

services:
  - name: La bonne boite
    url: http://labonneboite.pole-emploi.fr
    description: Votre adresse se complète au fils de sa saisie
    api:
      - name: BAN
        url: api/ban
    screenshot: ecran_labonneboite
    reutilisation: En utilisant l'auto-completion de la Base Adresse Nationale (BAN), laBonneBoite simplifie la saisie d'une adresse pour l'usager en recherche d'emploi. Les adresses fournies par la BAN sont géocodées en latitude et longitude, ce qui permet ensuite à laBonneBoite de cibler les entreprises dans un rayon géographique autour de l'adresse.

  - name: Mes aides
    url: http://mes-aides.gouv.fr
    description: Simulez toutes vos aides sociales en ligne
    api:
      - name: OpenFisca
        url: openfisca
    screenshot: ecran_mesaides
    reutilisation: Dans le maquis des aides sociales, c'est à l'usager de déterminer le bon guichet pour connaître ses droits. Grâce à mes-aides, l'usager peut en quelques clics découvrir toutes les aides auxquelles il a droit en décrivant sa situation une seule fois. Le simulateur OpenFisca prend en compte toute la législation fiscale et sociale et permet donc de répondre précisément à la question "à quelles aides ai-je droit ?

  - name: Vitiplantation
    url: http://www.franceagrimer.fr/filiere-vin-et-cidriculture/Vin/En-un-clic/Vitiplantation
    description: En quelques clics, les viticulteurs gèrent leur parcelle
    api:
      - name: API Carto
        url: apicarto
    screenshot: ecran_vitiplantation
    reutilisation: Pour un vigneron, réaliser un acte de gestion sur ses parcelles est un exercice compliqué car le formulaire Cerfa se prête mal à l'échange d'informations géographiques avec l'administration et conduit à des approximations, des erreurs et beaucoup de ressaisies dans les services instructeurs de FranceAgrimer. Pour réaliser des économies et simplifier la vie des vignerons, le téléservice Vitiplantation permet d'affecter à la vigne de nouvelles parcelles en quelques clics grâce à l'API Carto.

  - name: MPS
    url: https://www.marches-securises.fr/entreprise
    description: Un siret pour candidater uniquement pour un marché public
    api:
      - name: API Entreprise
        url: apientreprise
      - name: API Carto
        url: apicarto
    screenshot: ecran_MPS
    reutilisation: En adoptant MPS, la plateforme de dématérialisation Marchés Sécurisés permet aux entreprises de candidater à un marché public sans remplir de formulaire complexe ni fournir de pièces justificatives. Les entreprises saisisissent leur numéro de SIRET, valident leur consentement à ce que l'acheteur public accède aux attestations sociales ou fiscales, et déposent simplement leur offre.

# Build settings
markdown: kramdown
